language: php
sudo: false
php:
  - 5.6
before_install:
  - composer self-update
install:
  - composer install
  - ./scripts/fixtures.sh
script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpspec run
  - ./vendor/bin/phpunit
